/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'selector',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  safelist: [
    'bg-dbx-blue', 'bg-dbx-blue-bg', 'bg-dbx-blue/30', 'text-dbx-blue', 'text-dbx-blue-dk',
    'border-dbx-blue', 'border-dbx-blue/20', 'border-l-dbx-blue', 'hover:bg-dbx-blue-dk',
    'dark:bg-dbx-green', 'dark:bg-dbx-green-bg/10', 'dark:bg-dbx-green/30', 'dark:text-dbx-green', 'dark:text-dbx-green-dk',
    'dark:border-dbx-green', 'dark:border-dbx-green/20', 'dark:border-l-dbx-green', 'dark:hover:bg-dbx-green-dk',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['DM Sans', 'system-ui', 'sans-serif'],
        mono: ['DM Mono', 'monospace'],
      },
      colors: {
        dbx: {
          red:        '#FF3522',
          'red-dk':   '#D92B1A',
          'red-lt':   '#E4C8C8',
          'red-bg':   '#F8EAE9',
          'red-bg-dk':'#2D1F1E',
          blue:       '#2E7DD1',
          'blue-bg':  '#E8F1FB',
          'blue-dk':  '#1A5BA0',
          green:      '#00A972',
          'green-bg': '#E6F9F1',
          'green-dk': '#0F6E56',
          amber:      '#E68A00',
          'amber-bg': '#FFF5E0',
          error:      '#E24B4A',
          navy:       '#1B3139',
          menu:       '#F7F7F7',
          gray: {
            50:  '#FAFAFA',
            100: '#F0F0F0',
            200: '#E0E0E0',
            300: '#BDBDBD',
            400: '#9E9E9E',
            500: '#757575',
            600: '#616161',
            700: '#3A3440',
            800: '#312B2F',
            900: '#1F272E',
            950: '#11171D',
          },
        },
      },
      boxShadow: {
        'dbx':      '0 1px 3px rgba(255,53,34,0.08), 0 1px 2px rgba(255,53,34,0.06)',
        'dbx-md':   '0 4px 12px rgba(255,53,34,0.10), 0 1px 3px rgba(255,53,34,0.06)',
        'dbx-glow': '0 0 16px rgba(255,53,34,0.15)',
        'node':     '0 1px 4px rgba(0,0,0,0.06)',
        'node-hover':'0 2px 8px rgba(0,0,0,0.10)',
      },
      animation: {
        'fade-in':  'fadeIn 0.2s ease-out',
        'slide-up': 'slideUp 0.25s ease-out',
        'pop':      'pop 0.3s cubic-bezier(0.34,1.56,0.64,1)',
        'fill-bar': 'fillBar 12s cubic-bezier(0.4,0,0.2,1) forwards',
      },
      keyframes: {
        fadeIn:  { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(6px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        pop:     { from: { opacity: '0', transform: 'scale(0.9)' }, to: { opacity: '1', transform: 'scale(1)' } },
        fillBar: { '0%': { width: '0%' }, '30%': { width: '40%' }, '60%': { width: '70%' }, '80%': { width: '85%' }, '100%': { width: '95%' } },
      },
    },
  },
  plugins: [],
}
